apiVersion: v2
description: Grants reporting microservice listenting to application created event
name: ffc-grants-reporting
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^1.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
